### ISSUE TITLE
babel-core (and babylon) depricated

### ISSUE THREAD

**Issue by LeifAndersen** [ocelot-ide/ElementaryJS#201]
Just a heads up, I notice that in your `pacage.json` file you are using `babel-core` as a dependency (and by proxy `babylon` for parsing).

Those dependencies have seemed to move to `@babel/core` and `@babel/parser` now.

**Comment by arjunguha** [comment]
Yes. However, those are newer version of babel that have two issues:

1. They are significantly different from babel-core
2. Their performance was terrible when I last checked. IIRC, the version of Babel used in Stopify updates the AST in-place. The newer versions of Babel do not use in-place updates, which kills performance. It matters on the large programs that come out of compilers.

I attempted this 2-3 years ago. It took dozens of hours of work, which were ultimately fruitless. Maybe things are different now, if you want to attempt it. But, I would first verify that modern Babel can apply a number of transformations *in-place*.
